import {
  Controller,
  Get,
  Patch,
  Delete,
  Param,
  UseGuards,
  Query,
  Body,
} from '@nestjs/common';
import { CustomersService } from './customers.service';
import { UpdateCustomerDto } from './dto/customers.dto';
import { AuthGuard } from '../common/guards/auth.guard';
import { TenantGuard } from '../common/guards/tenant.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { Roles } from '../common/decorators/roles.decorator';
import { CurrentTenant } from '../common/decorators/current-tenant.decorator';
import type { Tenant } from '@prisma/client';

/**
 * Customers are auto-generated by the system when orders or reservations are
 * created — staff must NOT create them manually. This controller therefore
 * exposes only read + update + soft-delete operations.
 */
@Controller('/customers')
@UseGuards(AuthGuard, TenantGuard, RolesGuard)
export class CustomersController {
  constructor(private readonly customersService: CustomersService) {}

  @Get()
  @Roles('owner', 'manager', 'waiter', 'cashier')
  findAll(@CurrentTenant() tenant: Tenant | undefined, @Query() filters: any) {
    return this.customersService.findAll(tenant?.id, filters);
  }

  @Get(':id')
  @Roles('owner', 'manager', 'waiter', 'cashier')
  findOne(
    @CurrentTenant() tenant: Tenant | undefined,
    @Param('id') id: string,
  ) {
    return this.customersService.findOne(tenant?.id, id);
  }

  @Patch(':id')
  @Roles('owner', 'manager')
  update(
    @CurrentTenant() tenant: Tenant | undefined,
    @Param('id') id: string,
    @Body() data: UpdateCustomerDto,
  ) {
    return this.customersService.update(tenant?.id, id, data);
  }

  @Delete(':id')
  @Roles('owner', 'manager')
  remove(@CurrentTenant() tenant: Tenant | undefined, @Param('id') id: string) {
    return this.customersService.remove(tenant?.id, id);
  }
}
