import {
  Controller,
  Get,
  Patch,
  Delete,
  Param,
  UseGuards,
  Query,
  Body,
} from '@nestjs/common';
import { CustomersService } from './customers.service';
import { UpdateCustomerDto } from './dto/customers.dto';
import { AuthGuard } from '../common/guards/auth.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { Roles } from '../common/decorators/roles.decorator';

/**
 * Customers are auto-generated by the system when orders or reservations are
 * created — staff must NOT create them manually. This controller therefore
 * exposes only read + update + soft-delete operations.
 */
@Controller('/customers')
@UseGuards(AuthGuard, RolesGuard)
export class CustomersController {
  constructor(private readonly customersService: CustomersService) {}

  @Get()
  @Roles('owner', 'manager', 'waiter', 'cashier')
  findAll(@Query() filters: any) {
    return this.customersService.findAll(filters);
  }

  @Get(':id')
  @Roles('owner', 'manager', 'waiter', 'cashier')
  findOne(@Param('id') id: string) {
    return this.customersService.findOne(id);
  }

  @Patch(':id')
  @Roles('owner', 'manager')
  update(@Param('id') id: string, @Body() data: UpdateCustomerDto) {
    return this.customersService.update(id, data);
  }

  @Delete(':id')
  @Roles('owner', 'manager')
  remove(@Param('id') id: string) {
    return this.customersService.remove(id);
  }
}
