import api from '@/lib/api-client';

/**
 * Customers are auto-generated by the system (from orders and reservations).
 * The create endpoint has been removed — do NOT call createCustomer from the UI.
 */
export const customersService = {
  getCustomers: async (params?: any) => {
    return api.get('/customers', { params });
  },

  getCustomerById: async (id: string) => {
    return api.get(`/customers/${id}`);
  },

  updateCustomer: async (id: string, customerData: any) => {
    return api.patch(`/customers/${id}`, customerData);
  },

  deleteCustomer: async (id: string) => {
    return api.delete(`/customers/${id}`);
  },
};
